name: TestBOT
description: testing...
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0'

dependencies:
  dotenv: ^3.0.0
  nyxx:
    git:
      url: git://github.com/l7ssha/nyxx.git
  yaml: ^3.1.0
